feat: pipe checks

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,7 +75,12 @@ jobs:
         run: npm run test
 
       - name: Test build cache (full cache)
-        run: npm run test
+        run: |
+          npm run test | tee test-output.log
+          if ! grep -q "FULL TURBO" test-output.log; then
+            echo "FULL TURBO not found in output"
+            exit 1
+          fi
 
   test-action-windows:
     name: GitHub Actions Test (Windows)
@@ -109,4 +114,9 @@ jobs:
         run: npm run test
 
       - name: Test build cache (full cache)
-        run: npm run test
+        run: |
+          npm run test | tee test-output.log
+          if ! findstr "FULL TURBO" test-output.log; then
+            echo "FULL TURBO not found in output"
+            exit 1
+          fi
